version: '3.8'
name: pet-service
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: db-pet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-pet-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
volumes:
  db-pet-data: { }
